### ISSUE TITLE
Cucumber Feature:29 fails 'home page' check

### ISSUE THREAD

**Issue by d-gallagher** [gmit-sweng-20/ca5-bdd-tdd-cycle-d-gallagher#6]
Hi John,
Question about the Scenario for feature:29
```
Then I should be on the home page 
      expected: "/movies"
      got: "/movies/3/director" 
```

As far as I can tell I am routing the user back to the home page with 
```
redirect_to movies_path
```
in the [search_directors](https://github.com/gmit-sweng-20/ca5-bdd-tdd-cycle-d-gallagher/blob/c48840c40f38f6859114c54d0bfc310053907d77/rottenpotatoes/app/controllers/movies_controller.rb#L57) function call.. 
But this error says im sending the user to  endpoint '/movies/3/director'..
I get the same result if i swap 
```
movies_path 
```
for 
```
root_path
``` 
I thought root might have solved it since looking at rake routes it redirects to /movies but no dice.. 
Have I missed something elsewhere..
Any advice would be great!

**Comment by john-french** [comment]
Looking into in now @d-gallagher. Not immediately obvious what's going on.

**Comment by john-french** [comment]
Just FYI, I've heard from another student that him and someone else have the same issue. Still looking into it

**Comment by d-gallagher** [comment]
Sound John, thanks for the heads up and for taking a look.

**Comment by john-french** [comment]
Figured it out. In the test data setup in the `Before` step, there's the following:
```gherkin
  | Alien        | R      |              |   1979-05-25 |
```

The `director` field for Alien is being populated with something, the something just happens to be empty spaces.
So this
```ruby
      if @movie.director.nil?
```
returns false for the Alien record above, because the `director` field isn't `nil`. But it is `blank`. So try this instead:
```ruby
    if !@movie.director.blank?
```

**Comment by john-french** [comment]
One other thing to note: how come the app works fine but the test failed? They're using different data. The test data comes from the `Before` step (see previous comment), where the `director` field for Alien is **not** nil. 
The app data comes from `db/seeds.rb`, where `director` for Alien **is** nil.
```ruby
{:title => 'Alien', :rating => 'R', :release_date => '21-May-1979'},
```

**Comment by d-gallagher** [comment]
Thanks for the help with that, tests now confirmed passing.
Quick question:
When you refer to 'In the test data setup in the Before step',  
Is that the directors.feature file? - where we set up the table  
Given some following condition
//table with data is here

**Comment by john-french** [comment]
Exactly

**Comment by d-gallagher** [comment]
Great, thanks again for the help.
Closing out the issue.
