### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by john-french** [gmit-sweng-20/ca5-bdd-tdd-cycle-d-gallagher#7]
- Would be good to verify if correct template rendered. Also seems to be some duplication here?
https://github.com/gmit-sweng-20/ca5-bdd-tdd-cycle-d-gallagher/blob/df8902bf5203032ac202947b6d13ed03fe112a11/rottenpotatoes/spec/controllers/movies_controller_spec.rb#L21
- These don't test anything, because there's no assertions (expectations, i.e. `expect...`)
https://github.com/gmit-sweng-20/ca5-bdd-tdd-cycle-d-gallagher/blob/df8902bf5203032ac202947b6d13ed03fe112a11/rottenpotatoes/spec/controllers/movies_controller_spec.rb#L35
https://github.com/gmit-sweng-20/ca5-bdd-tdd-cycle-d-gallagher/blob/df8902bf5203032ac202947b6d13ed03fe112a11/rottenpotatoes/spec/controllers/movies_controller_spec.rb#L42
- Otherwise controller tests are good
- Model tests are good

Please close this issue to acknowledge receipt of feedback.

**Comment by d-gallagher** [comment]
Hi John,

Thanks for the feedback.

Regards,

David.
